### ISSUE TITLE
 WebViewJavascriptBridge is not defined

### ISSUE THREAD

**Issue by yubaokang** [epoll-j/bridge_webview_flutter#3]
I/chromium(12549): [INFO:CONSOLE(406)] "Uncaught ReferenceError: WebViewJavascriptBridge is not defined", source: http://192.168.2.117:8080/pages_home.0d3691edee544a7a186c.js (406)

**Comment by yubaokang** [comment]
> I/chromium(12549): [INFO:CONSOLE(406)] "Uncaught ReferenceError: WebViewJavascriptBridge is not defined", source: http://192.168.2.117:8080/pages_home.0d3691edee544a7a186c.js (406)

**Comment by yubaokang** [comment]
> I/chromium(12549): [INFO:CONSOLE(406)] "Uncaught ReferenceError: WebViewJavascriptBridge is not defined", source: http://192.168.2.117:8080/pages_home.0d3691edee544a7a186c.js (406)

**Comment by yubaokang** [comment]
D/EgretLoader(21489): EgretLoader(Context context)
D/EgretLoader(21489): The context is not activity
I/flutter (21489): Caught error: MissingPluginException(No implementation found for method registerHandler on channel plugins.flutter.io/webview_1)
I/flutter (21489): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
I/flutter (21489): <asynchronous suspension>
I/flutter (21489): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
I/flutter (21489): #2      MethodChannelWebViewPlatform.registerHandler (package:bridge_webview_flutter/src/webview_method_channel.dart:216:21)
I/flutter (21489): #3      WebViewController.registerHandler (package:bridge_webview_flutter/webview_flutter.dart:682:39)
I/flutter (21489): #4      _VRWebView3State.build.<anonymous closure>.<anonymous closure> (package:flutter_app/module/vr/vr_webview3.dart:59:37)
I/flutter (21489): #5      _BridgeWebViewState._onWebViewPlatformCreated (package:bridge_webview_flutter/webview_flutter.dart:375:30)
I/flutter (21489): #6      AndroidWebView.build.<anonymous closure> (package:bridge_webview_flutter/src/webview_android.dart:46:35)
I/flutter (21489): #7      AndroidViewController._create (package:flutter/src/services/platform_views.dart:637:15)
I/flutter (21489): #8      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter (21489): #9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter (21489): #10     _FutureL
W/ContentCatcher(21489): Failed to notify a WebView

报错，咋整胸弟

**Comment by epoll-j** [comment]
> D/EgretLoader(21489): EgretLoader(Context context)
> D/EgretLoader(21489): The context is not activity
> I/flutter (21489): Caught error: MissingPluginException(No implementation found for method registerHandler on channel plugins.flutter.io/webview_1)
> I/flutter (21489): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
> I/flutter (21489): 
> I/flutter (21489): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
> I/flutter (21489): #2 MethodChannelWebViewPlatform.registerHandler (package:bridge_webview_flutter/src/webview_method_channel.dart:216:21)
> I/flutter (21489): #3 WebViewController.registerHandler (package:bridge_webview_flutter/webview_flutter.dart:682:39)
> I/flutter (21489): #4 _VRWebView3State.build.. (package:flutter_app/module/vr/vr_webview3.dart:59:37)
> I/flutter (21489): #5 _BridgeWebViewState._onWebViewPlatformCreated (package:bridge_webview_flutter/webview_flutter.dart:375:30)
> I/flutter (21489): #6 AndroidWebView.build. (package:bridge_webview_flutter/src/webview_android.dart:46:35)
> I/flutter (21489): #7 AndroidViewController._create (package:flutter/src/services/platform_views.dart:637:15)
> I/flutter (21489): #8 _rootRunUnary (dart:async/zone.dart:1198:47)
> I/flutter (21489): #9 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> I/flutter (21489): #10 _FutureL
> W/ContentCatcher(21489): Failed to notify a WebView
> 
> 报错，咋整胸弟

方便贴一下相关的代码吗

**Comment by SmileJason** [comment]
library not found for -lWebViewJavascriptBridge
