### ISSUE TITLE
点击网页一个按钮，app crash ,android Q出现的问题

### ISSUE THREAD

**Issue by andyxiaoxi** [epoll-j/bridge_webview_flutter#5]
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err: java.lang.ClassCastException: $Proxy2 cannot be cast to android.view.WindowManagerImpl
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at android.view.Window.setWindowManager(Window.java:778)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at android.view.Window.setWindowManager(Window.java:760)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at android.app.Dialog.<init>(Dialog.java:209)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at android.app.AlertDialog.<init>(AlertDialog.java:214)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at android.app.AlertDialog$Builder.create(AlertDialog.java:1130)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at py.<init>(PG:6)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at org.chromium.content.browser.input.SelectPopup.show(PG:12)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at android.os.Looper.loop(Looper.java:181)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7520)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
2020-08-22 14:45:10.593 25131-25131/com.ccb.gongzu W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-08-22 14:45:10.596 25131-25131/com.ccb.gongzu A/chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
2020-08-22 14:45:11.096 25131-25131/com.ccb.gongzu A/libc: Fatal signal 5 (SIGTRAP), code 0 (SI_USER) in tid 25131 (com.ccb.gongzu), pid 25131 (com.ccb.gongzu)

**Comment by epoll-j** [comment]
这个库不再维护了，因为跟webview耦合度太高了，把jsbridge内容分离出来重写了一个[plugin](https://github.com/epoll-j/flutter_jsbridge_plugin)
